import type { Definition, Port, Parameter } from './model';

const input = (id: string, name = id, side: Port['side'] = 'left'): Port => ({
  id,
  name,
  direction: 'input',
  domain: 'signal',
  side,
});
const output = (
  id: string,
  name = id,
  unit = '',
  side: Port['side'] = 'right',
): Port => ({ id, name, direction: 'output', domain: 'signal', side, unit });
const p = (
  id: string,
  name: string,
  value: number,
  unit = '',
  min?: number,
): Parameter => ({ id, name, value, unit, min });
const physical = (
  id: string,
  name: string,
  domain: Port['domain'],
  side: Port['side'],
): Port => ({ id, name, domain, side, direction: 'physical' });
const signal = (
  kind: string,
  name: string,
  symbol: string,
  ports: Port[],
  equations: string,
  parameters: Parameter[] = [],
  declarations = '',
  description = name,
  keywords: string[] = [],
): Definition => ({
  kind,
  name,
  symbol,
  domain: 'signal',
  description,
  ports,
  equations,
  parameters,
  declarations,
  keywords,
});

export const extraBlocks: Definition[] = [
  signal(
    'ramp',
    'Ramp',
    'ramp',
    [output('y')],
    'y = if time < startTime then 0 else slope*(time-startTime);',
    [p('slope', 'Slope', 1, '1/s'), p('startTime', 'Start time', 0, 's', 0)],
    '',
    'A linearly increasing signal after a start time.',
    ['source', 'reference'],
  ),
  signal(
    'sine',
    'Sine wave',
    'sine',
    [output('y')],
    'y = offset + amplitude*sin(6.283185307179586*frequency*time + phase);',
    [
      p('amplitude', 'Amplitude', 1),
      p('frequency', 'Frequency', 1, 'Hz', 0),
      p('phase', 'Phase', 0, 'rad'),
      p('offset', 'Offset', 0),
    ],
    '',
    'A continuous sinusoid.',
    ['source', 'oscillator', 'wave'],
  ),
  signal(
    'pulse',
    'Pulse',
    'pulse',
    [output('y')],
    'y = if mod(time - startTime + period, period) < width*period then amplitude else 0;',
    [
      p('amplitude', 'Amplitude', 1),
      p('period', 'Period', 1, 's', 0.0001),
      p('width', 'Duty cycle', 0.5, '', 0),
      p('startTime', 'Start time', 0, 's', 0),
    ],
    '',
    'A periodic rectangular pulse.',
    ['source', 'square', 'pwm'],
  ),
  signal(
    'clock',
    'Clock',
    'clock',
    [output('y', 't', 's')],
    'y = time;',
    [],
    '',
    'Simulation time as a signal.',
    ['source', 'time'],
  ),
  signal(
    'product',
    'Product',
    '×',
    [input('a'), input('b', 'b', 'bottom'), output('y')],
    'y = a * b;',
    [],
    '',
    'Multiply two signals.',
    ['math', 'multiply'],
  ),
  signal(
    'divide',
    'Divide',
    '÷',
    [input('a'), input('b', 'b', 'bottom'), output('y')],
    'y = a / b;',
    [],
    '',
    'Divide two signals: y = a / b. Keep the denominator away from zero.',
    ['math'],
  ),
  signal(
    'abs',
    'Abs',
    '|u|',
    [input('u'), output('y')],
    'y = abs(u);',
    [],
    '',
    'Absolute value.',
    ['math'],
  ),
  signal(
    'sign',
    'Sign',
    'sgn',
    [input('u'), output('y')],
    'y = if u > 0 then 1 else (if u < 0 then -1 else 0);',
    [],
    '',
    'Sign of the input: −1, 0, or 1.',
    ['math'],
  ),
  signal(
    'sqrt',
    'Sqrt',
    '√',
    [input('u'), output('y')],
    'y = sqrt(max(0, u));',
    [],
    '',
    'Square root of a non-negative input.',
    ['math'],
  ),
  signal(
    'min',
    'Min',
    'min',
    [input('a'), input('b', 'b', 'bottom'), output('y')],
    'y = min(a, b);',
    [],
    '',
    'The smaller of two signals.',
    ['math'],
  ),
  signal(
    'max',
    'Max',
    'max',
    [input('a'), input('b', 'b', 'bottom'), output('y')],
    'y = max(a, b);',
    [],
    '',
    'The larger of two signals.',
    ['math'],
  ),
  signal(
    'sineOp',
    'Sin',
    'sin',
    [input('u'), output('y')],
    'y = sin(u);',
    [],
    '',
    'Sine of the input, in radians.',
    ['math', 'trig'],
  ),
  signal(
    'cosineOp',
    'Cos',
    'cos',
    [input('u'), output('y')],
    'y = cos(u);',
    [],
    '',
    'Cosine of the input, in radians.',
    ['math', 'trig'],
  ),
  signal(
    'unaryMinus',
    'Unary minus',
    '−',
    [input('u'), output('y')],
    'y = -u;',
    [],
    '',
    'Negate a signal.',
    ['math', 'invert', 'negate'],
  ),
  signal(
    'power',
    'Power',
    'uⁿ',
    [input('u'), output('y')],
    'y = u^n;',
    [p('n', 'Exponent', 2)],
    '',
    'Raise a signal to a real exponent.',
    ['math', 'exp'],
  ),
  signal(
    'derivative',
    'Derivative',
    's',
    [input('u'), output('y')],
    'der(x) = (u - x)/tau;\ny = (u - x)/tau;',
    [p('tau', 'Filter time', 0.01, 's', 0.00001)],
    'Real x(start=0, fixed=true);',
    'Filtered derivative du/dt.',
    ['continuous', 'diff'],
  ),
  signal(
    'secondOrder',
    'Second-order',
    'ωn,ζ',
    [input('u'), output('y')],
    'der(x1) = x2;\nder(x2) = wn*wn*(u - x1) - 2*zeta*wn*x2;\ny = x1;',
    [
      p('wn', 'Natural frequency', 10, 'rad/s', 0.01),
      p('zeta', 'Damping ratio', 0.7, '', 0),
    ],
    'Real x1(start=0, fixed=true);\nReal x2(start=0, fixed=true);',
    'A second-order transfer function ωn² / (s² + 2ζωn s + ωn²).',
    ['continuous', 'tf', 'transfer'],
  ),
  signal(
    'delay',
    'Transport delay',
    'e⁻sT',
    [input('u'), output('y')],
    'y = delay(u, T);',
    [p('T', 'Delay', 0.05, 's', 0)],
    '',
    'A pure time delay.',
    ['continuous', 'delay'],
  ),
  {
    ...signal(
      'pid',
      'PID',
      'PID',
      [input('u', 'e'), output('y')],
      'der(xi) = u;\nder(xf) = (u - xf)/tf;\ny = kp*u + ki*xi + kd*(u - xf)/tf;',
      [
        p('kp', 'Proportional gain', 1),
        p('ki', 'Integral gain', 0.5),
        p('kd', 'Derivative gain', 0.05),
        p('tf', 'Derivative filter', 0.01, 's', 0.0001),
      ],
      'Real xi(start=0, fixed=true);\nReal xf(start=0, fixed=true);',
      'Parallel PID with a filtered derivative term.',
      ['control', 'regulator'],
    ),
    controller: true,
  },
  {
    ...signal(
      'discretePID',
      'Discrete PID',
      'PID(z)',
      [input('reference', 'ref'), input('measured', 'meas'), output('y')],
      'when sample(0, samplePeriod) then\n  e = reference - measured;\n  integral = max(-limit, min(limit, pre(integral) + samplePeriod*ki*e));\n  derivative = (filterTime*pre(derivative) + kd*(e - pre(errorPrev)))/(filterTime + samplePeriod);\n  errorPrev = e;\n  y = max(-limit, min(limit, kp*e + integral + derivative));\nend when;',
      [
        p('kp', 'Proportional gain', 1),
        p('ki', 'Integral gain', 0.5),
        p('kd', 'Derivative gain', 0.05),
        p('filterTime', 'Derivative filter', 0.01, 's', 0.0001),
        p('limit', 'Output limit', 10, '', 0.001),
        p('samplePeriod', 'Sample period', 0.001, 's', 0.0001),
      ],
      'discrete Real e(start=0, fixed=true);\ndiscrete Real integral(start=0, fixed=true);\ndiscrete Real derivative(start=0, fixed=true);\ndiscrete Real errorPrev(start=0, fixed=true);',
      'Sampled PID with a filtered derivative, a clamped integral, and output saturation. Every state updates at the sample instant, so exported C reproduces it exactly.',
      ['control', 'regulator', 'discrete', 'sampled', 'export', 'c'],
    ),
    controller: true,
  },
  signal(
    'unitDelay',
    'Unit delay',
    'z⁻¹',
    [input('u'), output('y')],
    'when sample(0, Ts) then\n  y = pre(stored);\n  stored = u;\nend when;',
    [p('Ts', 'Sample period', 0.001, 's', 0.0001)],
    'discrete Real stored(start=0, fixed=true);',
    'One-sample delay.',
    ['discrete', 'z', 'delay'],
  ),
  signal(
    'zoh',
    'Zero-order hold',
    'ZOH',
    [input('u'), output('y')],
    'when sample(0, Ts) then\n  y = u;\nend when;',
    [p('Ts', 'Sample period', 0.001, 's', 0.0001)],
    '',
    'Sample and hold.',
    ['discrete', 'sample'],
  ),
  signal(
    'discreteIntegrator',
    'Discrete integrator',
    'Ts/z-1',
    [input('u'), output('y')],
    'when sample(0, Ts) then\n  x = pre(x) + Ts*u;\nend when;\ny = x;',
    [p('Ts', 'Sample period', 0.001, 's', 0.0001)],
    'discrete Real x(start=0, fixed=true);',
    'Sampled integrator accumulating the current input at each sample.',
    ['discrete', 'sum'],
  ),
  signal(
    'deadzone',
    'Dead zone',
    'dead',
    [input('u'), output('y')],
    'y = if u > start then u - start else (if u < -start then u + start else 0);',
    [p('start', 'Half-width', 0.1, '', 0)],
    '',
    'Zero output inside ±half-width.',
    ['nonlinear'],
  ),
  signal(
    'relay',
    'Relay',
    'relay',
    [input('u'), output('y')],
    'y = if u >= offSwitch then onValue else offValue;',
    [
      p('onValue', 'On value', 1),
      p('offValue', 'Off value', -1),
      p('offSwitch', 'Switch level', 0),
    ],
    '',
    'A two-level relay.',
    ['nonlinear', 'hysteresis'],
  ),
  signal(
    'rateLimiter',
    'Rate limiter',
    'du/dt',
    [input('u'), output('y')],
    'der(x) = if u > x then min(rising, (u - x)*1000) else max(-falling, (u - x)*1000);\ny = x;',
    [
      p('rising', 'Rising limit', 10, '1/s', 0),
      p('falling', 'Falling limit', 10, '1/s', 0),
    ],
    'Real x(start=0, fixed=true);',
    'Limits how fast a signal may change.',
    ['nonlinear', 'slew'],
  ),
  signal(
    'mux',
    'Mux',
    'mux',
    [input('u1', '1'), input('u2', '2'), input('u3', '3'), output('y')],
    'y = {u1, u2, u3};',
    [],
    '',
    'Joins signals into one vector wire, in order. Set the number of inputs in its properties; an input may itself be a vector.',
    ['routing', 'bus', 'bundle', 'vector', 'concatenate'],
  ),
  signal(
    'demux',
    'Demux',
    'demux',
    [input('u'), output('y1', '1'), output('y2', '2'), output('y3', '3')],
    'y1 = u[1];\ny2 = u[2];\ny3 = u[3];',
    [],
    '',
    'Splits a vector wire into its signals, in order. Set the number of outputs in its properties.',
    ['routing', 'bus', 'vector', 'split'],
  ),
  signal(
    'busCreator',
    'Bus Creator',
    'bus',
    [input('u1', 'signal1'), input('u2', 'signal2'), output('y', 'bus')],
    'y = {u1, u2};',
    [],
    '',
    'Bundles named signals into one bus wire. Each input is named in its properties; a bus can carry another bus.',
    ['routing', 'bus', 'bundle', 'named', 'signals'],
  ),
  signal(
    'busSelector',
    'Bus Selector',
    'select',
    [input('u', 'bus'), output('y1', 'signal1')],
    'y1 = u[1];',
    [],
    '',
    'Picks signals out of a bus by name. Choose the signals in its properties; each becomes an output.',
    ['routing', 'bus', 'select', 'named', 'signals'],
  ),
  signal(
    'switch2',
    'Switch',
    'switch',
    [
      input('u1', 'u₁'),
      input('sel', 'sel', 'bottom'),
      input('u3', 'u₂'),
      output('y'),
    ],
    'y = if sel >= threshold then u1 else u3;',
    [p('threshold', 'Threshold', 0)],
    '',
    'Pass u₁ when the control is above threshold, otherwise u₂.',
    ['routing', 'logic'],
  ),
  signal(
    'manualSwitch',
    'Manual switch',
    '1|2',
    [input('u1', '1'), input('u2', '2', 'bottom'), output('y')],
    'y = if sel >= 1.5 then u2 else u1;',
    [p('sel', 'Select 1 or 2', 1, '', 1)],
    '',
    'Pick an input with a parameter. 1 uses the top input.',
    ['routing'],
  ),
  signal(
    'subsystem',
    'Subsystem',
    'sub',
    [input('u1', 'in1'), output('y1', 'out1')],
    'y1 = u1;',
    [],
    '',
    'A block with its own diagram inside, starting as in1 wired to out1. Double-click to open it. Drop a wire on it to add a port.',
    ['hierarchy', 'group', 'submodule', 'nested', 'ports'],
  ),
  signal(
    'emptySubsystem',
    'Empty subsystem',
    'sub',
    [],
    '',
    [],
    '',
    'A subsystem with nothing inside and no ports yet. Drop wires on it, or add ports in the inspector.',
    ['hierarchy', 'group', 'submodule', 'nested', 'blank'],
  ),
  signal(
    'terminator',
    'Terminator',
    'term',
    [input('u')],
    'unused = u;',
    [],
    'Real unused;',
    'Cap an unused output so the sheet stays tidy.',
    ['sink', 'ground'],
  ),
  signal(
    'scope',
    'Scope',
    'scope',
    [input('u')],
    'unused = u;',
    [],
    'Real unused;',
    'A drawing sink for a signal you intend to inspect.',
    ['sink', 'plot', 'scope'],
  ),
  signal(
    'display',
    'Display',
    '123',
    [input('u')],
    'unused = u;',
    [],
    'Real unused;',
    'A sink that marks a signal whose value you want to read. It adds no equations; read the value in Results.',
    ['sink', 'value'],
  ),
  {
    kind: 'resistor',
    name: 'Resistor',
    symbol: 'R',
    domain: 'electrical',
    description: 'An ideal resistor between two electrical pins.',
    ports: [
      physical('p', '+', 'electrical', 'left'),
      physical('n', '−', 'electrical', 'right'),
    ],
    parameters: [p('R', 'Resistance', 1, 'Ω', 0.000001)],
    equations: 'v = R*i;',
    keywords: ['electrical', 'ohm'],
  },
  {
    kind: 'capacitor',
    name: 'Capacitor',
    symbol: 'C',
    domain: 'electrical',
    description: 'An ideal capacitor.',
    ports: [
      physical('p', '+', 'electrical', 'left'),
      physical('n', '−', 'electrical', 'right'),
    ],
    parameters: [p('C', 'Capacitance', 0.001, 'F', 1e-12)],
    equations: 'i = C*der(v);',
    keywords: ['electrical'],
  },
  {
    kind: 'inductor',
    name: 'Inductor',
    symbol: 'L',
    domain: 'electrical',
    description: 'An ideal inductor.',
    ports: [
      physical('p', '+', 'electrical', 'left'),
      physical('n', '−', 'electrical', 'right'),
    ],
    parameters: [p('L', 'Inductance', 0.001, 'H', 1e-12)],
    equations: 'v = L*der(i);',
    keywords: ['electrical'],
  },
  {
    kind: 'diode',
    name: 'Diode',
    symbol: 'D',
    domain: 'electrical',
    description: 'An ideal diode. Forward conducting, reverse open.',
    ports: [
      physical('p', 'A', 'electrical', 'left'),
      physical('n', 'K', 'electrical', 'right'),
    ],
    parameters: [],
    equations: 'i = if v > 0 then v/1e-4 else 0;',
    keywords: ['electrical', 'semiconductor'],
  },
  {
    kind: 'springDamper',
    name: 'Spring-damper',
    symbol: 'c,d',
    domain: 'mechanical',
    description: 'Rotational spring and damper between two shafts.',
    ports: [
      physical('a', 'a', 'mechanical', 'left'),
      physical('b', 'b', 'mechanical', 'right'),
    ],
    parameters: [
      p('c', 'Stiffness', 10, 'N·m/rad', 0),
      p('d', 'Damping', 0.1, 'N·m·s', 0),
    ],
    equations: 'tau = c*phi + d*w;',
    keywords: ['mechanical', 'compliance'],
  },
  {
    kind: 'torqueSensor',
    name: 'Torque sensor',
    symbol: 'τ',
    domain: 'mechanical',
    description: 'Measures shaft torque without adding stiffness.',
    ports: [
      physical('a', 'a', 'mechanical', 'left'),
      physical('b', 'b', 'mechanical', 'right'),
      output('y', 'τ', 'N·m'),
    ],
    parameters: [],
    equations: 'y = tau;',
    keywords: ['mechanical', 'sensor'],
  },
  {
    kind: 'angleSensor',
    name: 'Angle sensor',
    symbol: 'θ',
    domain: 'mechanical',
    description:
      'Measures shaft angle in radians without loading the mechanical system.',
    ports: [
      physical('flange', 'shaft', 'mechanical', 'right'),
      output('y', 'y', 'rad', 'left'),
    ],
    parameters: [],
    equations: 'y = flange.phi;\nflange.tau = 0;',
    keywords: ['mechanical', 'sensor', 'position', 'encoder'],
  },
];
