import type { ExampleSpec } from './types';

export const control: ExampleSpec[] = [
  {
    id: 'control-loops',
    title: 'PI and PID loops',
    area: 'Control',
    summary:
      'The same first-order plant under a sampled PI, a continuous PID, and a sampled PID controller.',
    description:
      'Each plant is a lag with τ = 0.5 s and each loop follows a unit step at 0.1 s. The PI and sampled PID blocks take the reference and the measurement and form the error themselves; the continuous PID takes the error from a subtract block. All three reach the set point with no steady error, because each has integral action. Change a gain and run again to compare.',
    duration: 4,
    blocks: [
      [
        'ref1',
        'step',
        'Set point (PI)',
        [80, 144],
        { height: 1, startTime: 0.1 },
      ],
      [
        'pi',
        'pi',
        'PI (sampled)',
        [320, 160],
        { kp: 1, ki: 2, limit: 10, samplePeriod: 0.001 },
      ],
      [
        'plant1',
        'filter',
        'Plant (PI)',
        [560, 160],
        { tau: 0.5 },
        { label: 'above' },
      ],
      ['y1', 'gain', 'y (PI)', [760, 160], { k: 1 }],
      [
        'ref2',
        'step',
        'Set point (PID)',
        [80, 400],
        { height: 1, startTime: 0.1 },
      ],
      ['err', 'subtract', 'Error', [264, 400], {}, { label: 'above' }],
      ['pid', 'pid', 'PID', [432, 400], { kp: 1, ki: 2, kd: 0.05, tf: 0.01 }],
      [
        'plant2',
        'filter',
        'Plant (PID)',
        [608, 400],
        { tau: 0.5 },
        { label: 'above' },
      ],
      ['y2', 'gain', 'y (PID)', [784, 400], { k: 1 }],
      [
        'ref3',
        'step',
        'Set point (sampled PID)',
        [80, 624],
        { height: 1, startTime: 0.1 },
      ],
      [
        'dpid',
        'discretePID',
        'PID (sampled)',
        [320, 640],
        {
          kp: 1,
          ki: 2,
          kd: 0.05,
          filterTime: 0.01,
          limit: 10,
          samplePeriod: 0.001,
        },
      ],
      [
        'plant3',
        'filter',
        'Plant (sampled PID)',
        [560, 640],
        { tau: 0.5 },
        { label: 'above' },
      ],
      ['y3', 'gain', 'y (sampled PID)', [760, 640], { k: 1 }],
    ],
    links: [
      ['ref1.y', 'pi.reference'],
      ['pi.y', 'plant1.u'],
      ['plant1.y', 'y1.u'],
      ['plant1.y', 'pi.measured'],
      ['ref2.y', 'err.a'],
      ['err.y', 'pid.u'],
      ['pid.y', 'plant2.u'],
      ['plant2.y', 'y2.u'],
      ['plant2.y', 'err.b'],
      ['ref3.y', 'dpid.reference'],
      ['dpid.y', 'plant3.u'],
      ['plant3.y', 'y3.u'],
      ['plant3.y', 'dpid.measured'],
    ],
    plots: [
      {
        label: 'Plant outputs',
        series: ['ref1.y', 'y1.y', 'y2.y', 'y3.y'],
        labels: ['Set point', 'PI (sampled)', 'PID', 'PID (sampled)'],
      },
      {
        label: 'Controller outputs',
        series: ['pi.y', 'pid.y', 'dpid.y'],
        labels: ['PI (sampled)', 'PID', 'PID (sampled)'],
      },
    ],
    checks: [
      {
        signal: 'y1.y',
        value: 1,
        tol: 0.01,
        why: 'integral action removes the error',
      },
      {
        signal: 'y2.y',
        value: 1,
        tol: 0.01,
        why: 'integral action removes the error',
      },
      {
        signal: 'y3.y',
        value: 1,
        tol: 0.01,
        why: 'integral action removes the error',
      },
      { signal: 'y1.y', at: 0.09, value: 0, tol: 1e-9, why: 'before the step' },
    ],
    about: ['pi', 'pid', 'discretePID'],
  },
];
