import type { ExampleSpec } from './types';

const onTop = { ports: { u1: 'top', u2: 'bottom' }, label: 'right' } as const;

export const logic: ExampleSpec[] = [
  {
    id: 'logic-gates',
    title: 'Logic gates',
    area: 'Logic',
    summary:
      'AND, OR, XOR, NAND, NOR, and NOT on two Boolean pulse trains, and a Boolean turned into a number.',
    description:
      'A is true for the first half of every second, B for the first second of every two. Read the gates at 0.25 s (A and B true), 0.75 s (only B), and 1.75 s (neither): AND is true only at 0.25 s, OR at 0.25 and 0.75 s, XOR only at 0.75 s, NAND and NOR are their inverses, and NOT inverts A. Boolean to real turns the NOT output into 0 or 1 for arithmetic.',
    duration: 2,
    blocks: [
      ['A', 'booleanPulse', 'A', [80, 176], { width: 50, period: 1 }],
      ['B', 'booleanPulse', 'B', [80, 464], { width: 50, period: 2 }],
      ['gAnd', 'logicAnd', 'AND', [320, 320], {}, onTop],
      ['gOr', 'logicOr', 'OR', [544, 320], {}, onTop],
      ['gXor', 'logicXor', 'XOR', [768, 320], {}, onTop],
      ['gNand', 'logicNand', 'NAND', [992, 320], {}, onTop],
      ['gNor', 'logicNor', 'NOR', [1216, 320], {}, onTop],
      ['gNot', 'logicNot', 'NOT A', [1400, 176]],
      ['num', 'booleanToReal', 'Boolean to real', [1576, 176]],
    ],
    links: [
      ['A.y', 'gAnd.u1'],
      ['B.y', 'gAnd.u2'],
      ['A.y', 'gOr.u1'],
      ['B.y', 'gOr.u2'],
      ['A.y', 'gXor.u1'],
      ['B.y', 'gXor.u2'],
      ['A.y', 'gNand.u1'],
      ['B.y', 'gNand.u2'],
      ['A.y', 'gNor.u1'],
      ['B.y', 'gNor.u2'],
      ['A.y', 'gNot.u'],
      ['gNot.y', 'num.u'],
    ],
    plots: [
      { label: 'Inputs', series: ['A.y', 'B.y'], labels: ['A', 'B'] },
      {
        label: 'Gates',
        series: ['gAnd.y', 'gOr.y', 'gXor.y', 'gNand.y', 'gNor.y', 'num.y'],
        labels: ['AND', 'OR', 'XOR', 'NAND', 'NOR', 'NOT A as a number'],
      },
    ],
    checks: [
      { signal: 'gAnd.y', at: 0.25, value: 1, why: 'A and B' },
      { signal: 'gAnd.y', at: 0.75, value: 0, why: 'A is false' },
      { signal: 'gOr.y', at: 0.75, value: 1, why: 'B is true' },
      { signal: 'gOr.y', at: 1.75, value: 0, why: 'neither' },
      { signal: 'gXor.y', at: 0.25, value: 0, why: 'both true' },
      { signal: 'gXor.y', at: 0.75, value: 1, why: 'exactly one' },
      { signal: 'gNand.y', at: 0.25, value: 0, why: 'not (A and B)' },
      { signal: 'gNand.y', at: 0.75, value: 1, why: 'not (A and B)' },
      { signal: 'gNor.y', at: 0.75, value: 0, why: 'not (A or B)' },
      { signal: 'gNor.y', at: 1.75, value: 1, why: 'not (A or B)' },
      { signal: 'num.y', at: 0.25, value: 0, why: 'NOT A is false: 0' },
      { signal: 'num.y', at: 0.75, value: 1, why: 'NOT A is true: 1' },
    ],
    about: [
      'booleanPulse',
      'logicAnd',
      'logicOr',
      'logicXor',
      'logicNand',
      'logicNor',
      'logicNot',
      'booleanToReal',
    ],
  },
  {
    id: 'comparators',
    title: 'Comparators',
    area: 'Logic',
    summary:
      'A sine compared with thresholds, with a ramp, and through a hysteresis band.',
    description:
      'The sine is sin(πt); the ramp is t/4. Above threshold is true while the sine exceeds 0.5, Below threshold while it is under −0.5. Greater and Less compare the sine with the ramp. Hysteresis turns on above 0.5 and off only below −0.5: at 1.05 s the sine is slightly negative, so Above threshold is already false but Hysteresis is still true.',
    duration: 2,
    blocks: [
      ['s', 'sine', 'sin(πt)', [80, 176], { amplitude: 1, frequency: 0.5 }],
      ['r', 'ramp', 't / 4', [80, 464], { slope: 0.25, startTime: 0 }],
      [
        'above',
        'greaterThreshold',
        'Above 0.5',
        [320, 320],
        { threshold: 0.5 },
        { ports: { u: 'top' }, label: 'right' },
      ],
      [
        'below',
        'lessThreshold',
        'Below −0.5',
        [520, 320],
        { threshold: -0.5 },
        { ports: { u: 'top' }, label: 'right' },
      ],
      [
        'band',
        'boolHysteresis',
        'Hysteresis ±0.5',
        [720, 320],
        { uLow: -0.5, uHigh: 0.5 },
        { ports: { u: 'top' }, label: 'right' },
      ],
      ['gt', 'greater', 'Sine > ramp', [960, 320], {}, onTop],
      ['lt', 'less', 'Sine < ramp', [1208, 320], {}, onTop],
    ],
    links: [
      ['s.y', 'above.u'],
      ['s.y', 'below.u'],
      ['s.y', 'band.u'],
      ['s.y', 'gt.u1'],
      ['r.y', 'gt.u2'],
      ['s.y', 'lt.u1'],
      ['r.y', 'lt.u2'],
    ],
    plots: [
      { label: 'Inputs', series: ['s.y', 'r.y'], labels: ['sin(πt)', 't / 4'] },
      {
        label: 'Comparisons',
        series: ['above.y', 'below.y', 'band.y', 'gt.y', 'lt.y'],
        labels: [
          'Above 0.5',
          'Below −0.5',
          'Hysteresis',
          'Sine > ramp',
          'Sine < ramp',
        ],
      },
    ],
    checks: [
      { signal: 'above.y', at: 0.5, value: 1, why: 'sine 1 > 0.5' },
      { signal: 'above.y', at: 1.05, value: 0, why: 'sine −0.16 < 0.5' },
      { signal: 'below.y', at: 1.5, value: 1, why: 'sine −1 < −0.5' },
      { signal: 'below.y', at: 0.5, value: 0, why: 'sine 1' },
      {
        signal: 'band.y',
        at: 1.05,
        value: 1,
        why: 'on until the sine falls below −0.5',
      },
      {
        signal: 'band.y',
        at: 1.3,
        value: 0,
        why: 'sine −0.81 < −0.5 turned it off',
      },
      { signal: 'gt.y', at: 0.5, value: 1, why: '1 > 0.125' },
      { signal: 'gt.y', at: 1.5, value: 0, why: '−1 < 0.375' },
      { signal: 'lt.y', at: 1.5, value: 1, why: '−1 < 0.375' },
    ],
    about: [
      'greaterThreshold',
      'lessThreshold',
      'boolHysteresis',
      'greater',
      'less',
    ],
  },
  {
    id: 'latch-timer',
    title: 'Latch, timer, and sampler',
    area: 'Logic',
    summary:
      'Start and stop buttons set and reset a flip-flop, which times the run, gates a signal, and samples the start time.',
    description:
      'Start is pressed at 0.5 s and Stop at 1.5 s. Their rising edges set and reset the RS flip-flop, so Running is true from 0.5 s to 1.5 s. The timer counts seconds while Running is true. The logic switch passes the sine only while running and 0 otherwise. The triggered sampler reads the clock on the start edge and holds 0.5. Enable is a Boolean constant ANDed with Start: set it to false and nothing starts.',
    duration: 2,
    blocks: [
      ['enable', 'booleanConstant', 'Enable', [80, 96]],
      ['start', 'booleanStep', 'Start', [80, 224], { startTime: 0.5 }],
      ['stop', 'booleanStep', 'Stop', [80, 400], { startTime: 1.5 }],
      ['armed', 'logicAnd', 'Enabled start', [304, 160]],
      ['rise', 'edge', 'Start edge', [512, 160]],
      ['fall', 'edge', 'Stop edge', [512, 400]],
      ['latch', 'rsFlipFlop', 'Running', [736, 272]],
      ['timer', 'timer', 'Run time', [976, 176]],
      ['sine', 'sine', 'Sine 1 Hz', [736, 464], { amplitude: 1, frequency: 1 }],
      ['zero', 'constant', '0', [736, 592], { value: 0 }],
      ['gate', 'logicSwitch', 'Gated sine', [976, 400]],
      ['clock', 'clock', 'Clock', [736, 32]],
      [
        'hold',
        'triggeredSampler',
        'Start time',
        [976, 32],
        {},
        { ports: { trigger: 'top' } },
      ],
    ],
    links: [
      ['enable.y', 'armed.u1'],
      ['start.y', 'armed.u2'],
      ['armed.y', 'rise.u'],
      ['stop.y', 'fall.u'],
      ['rise.y', 'latch.S'],
      ['fall.y', 'latch.R'],
      ['latch.Q', 'timer.u'],
      ['latch.Q', 'gate.u2'],
      ['sine.y', 'gate.u1'],
      ['zero.y', 'gate.u3'],
      ['clock.y', 'hold.u'],
      ['rise.y', 'hold.trigger'],
    ],
    plots: [
      {
        label: 'Running',
        series: ['latch.Q', 'timer.y'],
        labels: ['Running', 'Run time'],
      },
      {
        label: 'Gated signal and start time',
        series: ['gate.y', 'hold.y'],
        labels: ['Gated sine', 'Start time'],
      },
    ],
    checks: [
      { signal: 'latch.Q', at: 0.4, value: 0, why: 'not started' },
      { signal: 'latch.Q', at: 1, value: 1, why: 'set at 0.5 s' },
      { signal: 'latch.Q', value: 0, why: 'reset at 1.5 s' },
      {
        signal: 'timer.y',
        at: 1,
        value: 0.5,
        tol: 1e-4,
        why: 'running for 0.5 s',
      },
      {
        signal: 'gate.y',
        at: 1.25,
        value: 1,
        tol: 1e-4,
        why: 'running: sin(2π·1.25) = 1',
      },
      { signal: 'gate.y', at: 1.75, value: 0, tol: 1e-9, why: 'stopped: 0' },
      {
        signal: 'hold.y',
        value: 0.5,
        tol: 1e-4,
        why: 'the clock at the start edge',
      },
    ],
    about: [
      'rsFlipFlop',
      'edge',
      'timer',
      'logicSwitch',
      'triggeredSampler',
      'booleanStep',
      'booleanConstant',
    ],
  },
  {
    id: 'thermostat',
    title: 'Thermostat',
    area: 'Logic',
    summary:
      'An on-off controller switches a 100 W heater to hold a room at 50 °C.',
    description:
      'The room is a 1000 J/K heat capacity losing heat to 20 °C outside through 2 W/K. The on-off controller turns the heater on below the set point minus half its 2 K band and off above it plus half, so after warming up for about 7 minutes the temperature cycles between 49 °C and 51 °C. Boolean to real scales the on command into 100 W of heat.',
    duration: 2000,
    blocks: [
      ['set', 'constant', 'Set point 50 °C', [80, 160], { value: 323.15 }],
      [
        'ctrl',
        'onOffController',
        'Thermostat',
        [304, 176],
        { bandwidth: 2 },
        { ports: { u: 'bottom' }, label: 'above' },
      ],
      [
        'power',
        'booleanToReal',
        'Heater 100 W',
        [528, 176],
        { realTrue: 100, realFalse: 0 },
      ],
      ['heater', 'prescribedHeatFlow', 'Heater', [720, 176]],
      [
        'room',
        'heatCapacitor',
        'Room',
        [912, 96],
        { C: 1000 },
        { label: 'above' },
      ],
      ['wall', 'thermalConductor', 'Walls 2 W/K', [1104, 176], { G: 2 }],
      [
        'outside',
        'fixedTemperature',
        'Outside 20 °C',
        [1296, 176],
        { T: 293.15 },
        { rotation: 180 },
      ],
      [
        'T',
        'temperatureSensor',
        'Room temperature',
        [720, 336],
        {},
        { rotation: 180 },
      ],
    ],
    links: [
      ['set.y', 'ctrl.reference'],
      ['T.T', 'ctrl.u'],
      ['ctrl.y', 'power.u'],
      ['power.y', 'heater.Q_flow'],
      ['heater.port', 'room.port'],
      ['room.port', 'wall.port_a'],
      ['wall.port_b', 'outside.port'],
      ['room.port', 'T.port'],
    ],
    plots: [
      { label: 'Room temperature', series: ['T.T'], labels: ['T (K)'] },
      { label: 'Heater command', series: ['power.y'], labels: ['Heat (W)'] },
    ],
    checks: [
      {
        signal: 'T.T',
        at: 0,
        value: 293.15,
        tol: 1e-6,
        why: 'starts at the outside temperature',
      },
      {
        signal: 'T.T',
        at: 1500,
        min: 321.9,
        max: 324.4,
        why: 'inside the 2 K band around 50 °C',
      },
      {
        signal: 'T.T',
        value: 323.15,
        tol: 1.25,
        why: 'inside the 2 K band around 50 °C',
      },
    ],
    about: ['onOffController'],
  },
];
