import type { ExampleSpec } from './types';

type Blocks = ExampleSpec['blocks'];
type Links = ExampleSpec['links'];
type Part = { blocks: Blocks; links: Links };
const merge = (...parts: Part[]): Part => ({
  blocks: parts.flatMap((p) => p.blocks),
  links: parts.flatMap((p) => p.links),
});

const syncSpeed = (2 * Math.PI * 50) / 2;

/** A three-phase source at (x, y) with its star point grounded below it. */
function mains(
  id: string,
  [x, y]: [number, number],
  V: number,
  name: string,
  tag: string,
): Part {
  return merge(
    {
      blocks: [
        [
          `${id}`,
          'threePhaseSource',
          name,
          [x, y],
          { V, f: 50 },
          { label: 'left' },
        ],
      ],
      links: [],
    },
    neutral(`${id}n`, [x, y + 48], tag, `${id}.plug_n`),
  );
}

/** A star point under a plug at (x, y), grounded: `plug` is the plug it closes. */
function neutral(
  id: string,
  [x, y]: [number, number],
  tag: string,
  plug: string,
): Part {
  return {
    blocks: [
      [
        `${id}star`,
        'star',
        `Star ${tag}`,
        [x, y + 80],
        {},
        { rotation: 90, label: 'right' },
      ],
      [`${id}g`, 'ground', `Ground ${tag}`, [x, y + 168]],
    ],
    links: [
      [plug, `${id}star.plug_p`],
      [`${id}star.pin_n`, `${id}g.p`],
    ],
  };
}

/** An AC machine started from the mains, with its speed measured. */
function lineStart(
  id: string,
  y: number,
  kind: string,
  name: string,
  tag: string,
  rms = 100,
): Part {
  return merge(
    mains(
      `${id}src`,
      [168, y],
      Math.round(rms * Math.SQRT2 * 10) / 10,
      `${rms} V rms ${tag}`,
      `${tag} supply`,
    ),
    neutral(`${id}n`, [456, y + 48], tag, `${id}.plug_sn`),
    {
      blocks: [
        [id, kind, name, [456, y], {}, { label: 'above' }],
        [
          `${id}w`,
          'rotSpeedSensor',
          `Speed ${tag}`,
          [696, y],
          {},
          { label: 'right' },
        ],
      ],
      links: [
        [`${id}src.plug_p`, `${id}.plug_sp`],
        [`${id}.flange`, `${id}w.flange`],
      ],
    },
  );
}

/** A DC supply at (x, y), grounded below. */
function dc(
  id: string,
  [x, y]: [number, number],
  V: number,
  name: string,
): Part {
  return {
    blocks: [
      [id, 'dcSource', name, [x, y], { V }, { label: 'left' }],
      [`${id}g`, 'ground', `Ground (${name})`, [x, y + 104]],
    ],
    links: [[`${id}.n`, `${id}g.p`]],
  };
}

// Radiation from the heatsink to 20 °C adds to convection: solve the heatsink balance.
const sigma = 5.670374419e-8;
const ambient = 293.15;
function heatsinkTemperature(q: number, g: number, gr: number) {
  let t = ambient + q / g;
  for (let i = 0; i < 50; i++) {
    const f = g * (t - ambient) + sigma * gr * (t ** 4 - ambient ** 4) - q;
    t -= f / (g + 4 * sigma * gr * t ** 3);
  }
  return t;
}
const hs = heatsinkTemperature(10, 5, 0.01);

export const physical: ExampleSpec[] = [
  {
    id: 'dc-machines',
    title: 'DC machines',
    area: 'Machines',
    summary:
      'Permanent-magnet, shunt, and series DC machines on 100 V, with their shaft speeds.',
    description:
      'All three have the same nominal point: 100 V, 100 A, 149.2 rad/s. The permanent-magnet and shunt machines run unloaded, so they speed up until their back EMF almost equals the supply: 100 V over a machine constant of 0.637 V·s/rad is 157 rad/s. The series machine would run away unloaded, so it drives a damper sized for its nominal torque and settles at its nominal speed.',
    duration: 1,
    ...merge(
      dc('va', [168, 184], 100, '100 V (PM)'),
      dc('vb', [168, 480], 100, '100 V (shunt)'),
      dc('vc', [168, 776], 100, '100 V (series)'),
      {
        blocks: [
          [
            'pm',
            'dcPmMachine',
            'PM machine',
            [424, 168],
            {},
            { label: 'above' },
          ],
          [
            'pmw',
            'rotSpeedSensor',
            'Speed (PM)',
            [648, 168],
            {},
            { label: 'right' },
          ],
          [
            'sh',
            'dcShuntMachine',
            'Shunt machine',
            [424, 464],
            {},
            { label: [0, 0] },
          ],
          [
            'shw',
            'rotSpeedSensor',
            'Speed (shunt)',
            [648, 464],
            {},
            { label: 'right' },
          ],
          [
            'se',
            'dcSeriesMachine',
            'Series machine',
            [424, 760],
            {},
            { label: [0, 0] },
          ],
          [
            'sew',
            'rotSpeedSensor',
            'Speed (series)',
            [648, 760],
            {},
            { label: 'right' },
          ],
          [
            'sed',
            'rotDamper',
            'Load 0.42 N·m·s',
            [648, 896],
            { d: 0.4223 },
            { label: 'above' },
          ],
          ['sef', 'rotFixed', 'Frame', [760, 992]],
        ],
        links: [
          ['va.p', 'pm.pin_ap'],
          ['va.n', 'pm.pin_an'],
          ['pm.flange', 'pmw.flange'],
          ['vb.p', 'sh.pin_ap'],
          ['vb.n', 'sh.pin_an'],
          ['vb.p', 'sh.pin_ep'],
          ['vb.n', 'sh.pin_en'],
          ['sh.flange', 'shw.flange'],
          ['vc.p', 'se.pin_ap'],
          ['se.pin_an', 'se.pin_ep'],
          ['se.pin_en', 'vc.n'],
          ['se.flange', 'sew.flange'],
          ['se.flange', 'sed.flange_a'],
          ['sed.flange_b', 'sef.flange'],
        ],
      },
    ),
    plots: [
      {
        label: 'Shaft speeds',
        series: ['pmw.w', 'shw.w', 'sew.w'],
        labels: ['PM', 'Shunt', 'Series'],
      },
    ],
    checks: [
      {
        signal: 'pmw.w',
        value: 100 / ((100 - 0.05 * 100) / 149.2),
        tol: 0.5,
        why: 'no load: V / k',
      },
      {
        signal: 'shw.w',
        value: 100 / ((100 - 0.05 * 100) / 149.2),
        tol: 0.5,
        why: 'no load at nominal field: V / k',
      },
      {
        signal: 'sew.w',
        value: 149.2,
        tol: 1.5,
        why: 'the damper is sized for the nominal point',
      },
    ],
    about: ['dcPmMachine', 'dcShuntMachine', 'dcSeriesMachine'],
  },
  {
    id: 'ac-machines',
    title: 'AC machines on the mains',
    area: 'Machines',
    summary:
      'Induction, permanent-magnet, and reluctance machines started straight from a 50 Hz supply.',
    description:
      'Each machine has two pole pairs, so its synchronous speed at 50 Hz is 2π · 50 / 2 = 157.1 rad/s. The induction machine accelerates until its slip is almost zero. The permanent-magnet and reluctance machines start as induction machines on their damper cages and then pull into step, running at exactly synchronous speed. The permanent-magnet machine is fed at its rated 112.3 V rms, which matches its magnet voltage; well below it, the magnets brake the start and it keeps slipping poles.',
    duration: 3,
    ...merge(
      lineStart('im', 176, 'inductionMachine', 'Induction', 'IM'),
      lineStart('pms', 544, 'pmSyncMachine', 'PM synchronous', 'PMSM', 112.3),
      lineStart('rel', 912, 'reluctanceMachine', 'Reluctance', 'SynRM'),
    ),
    plots: [
      {
        label: 'Shaft speeds',
        series: ['imw.w', 'pmsw.w', 'relw.w'],
        labels: ['Induction', 'PM synchronous', 'Reluctance'],
      },
    ],
    checks: [
      {
        signal: 'imw.w',
        value: syncSpeed,
        tol: 0.5,
        why: 'no load: slip close to zero',
      },
      {
        signal: 'pmsw.w',
        value: syncSpeed,
        tol: 0.1,
        why: 'in step at synchronous speed',
      },
      {
        signal: 'relw.w',
        value: syncSpeed,
        tol: 0.1,
        why: 'in step at synchronous speed',
      },
    ],
    about: [
      'inductionMachine',
      'pmSyncMachine',
      'reluctanceMachine',
      'threePhaseSource',
    ],
  },
  {
    id: 'position-sensors',
    title: 'Resolver and Hall sensor',
    area: 'Machines',
    summary:
      'A shaft turning at 10 rad/s read by a resolver, a Hall sensor, and an angle sensor.',
    description:
      'The shaft angle grows at 10 rad/s. The resolver (one pole pair) outputs the sine and cosine of the angle and their negatives. The Hall sensor reports the electrical angle of a two-pole-pair machine, 2 · φ + π wrapped to 0…2π, as its mounting offset puts π at zero shaft angle. The angle sensor reads the shaft angle itself.',
    duration: 1,
    blocks: [
      ['drive', 'constantSpeed', 'Shaft 10 rad/s', [168, 248], { w_fixed: 10 }],
      ['res', 'resolver', 'Resolver', [456, 104], { p: 1 }, { label: 'right' }],
      [
        'hall',
        'hallSensor',
        'Hall sensor',
        [456, 296],
        { p: 2 },
        { label: 'right' },
      ],
      [
        'ang',
        'angleSensor',
        'Shaft angle',
        [456, 440],
        {},
        { rotation: 180, label: 'right' },
      ],
    ],
    links: [
      ['drive.flange', 'res.flange'],
      ['drive.flange', 'hall.flange'],
      ['drive.flange', 'ang.flange'],
    ],
    plots: [
      {
        label: 'Resolver',
        series: ['res.sin', 'res.cos', 'res.nsin', 'res.ncos'],
        labels: ['sin', 'cos', '−sin', '−cos'],
      },
      {
        label: 'Angles',
        series: ['hall.y', 'ang.y'],
        labels: ['Hall θe', 'Shaft φ'],
      },
    ],
    checks: [
      {
        signal: 'res.sin',
        at: 0.1,
        value: Math.sin(1),
        tol: 1e-4,
        why: 'sin(10 rad/s · 0.1 s)',
      },
      {
        signal: 'res.cos',
        at: 0.1,
        value: Math.cos(1),
        tol: 1e-4,
        why: 'cos 1',
      },
      {
        signal: 'res.nsin',
        at: 0.1,
        value: -Math.sin(1),
        tol: 1e-4,
        why: '−sin 1',
      },
      {
        signal: 'hall.y',
        at: 0.1,
        value: 2 + Math.PI,
        tol: 1e-3,
        why: '2 · 1 rad + π',
      },
      {
        signal: 'hall.y',
        at: 0.5,
        value: 10 + Math.PI - 2 * 2 * Math.PI,
        tol: 1e-3,
        why: '2 · 5 + π, wrapped',
      },
      { signal: 'ang.y', value: 10, tol: 1e-4, why: '10 rad/s for 1 s' },
    ],
    about: ['resolver', 'hallSensor', 'constantSpeed'],
  },
  {
    id: 'three-phase-loads',
    title: 'Three-phase loads',
    area: '3-phase',
    summary:
      'A 10 V three-phase supply into a resistive star load, a series R–L star load, and a capacitor bank in delta.',
    description:
      'The resistive load takes a 1 A peak current per phase and a constant 15 W in total: 3 · (10 V)² / (2 · 10 Ω). The R–L load has 10 Ω of resistance and 10 Ω of reactance, so its 0.71 A current lags the voltage by 45°. The delta bank puts each 100 µF capacitor between two lines, at 17.3 V peak, so each line carries √3 times the capacitor current. Phase taps pick single phases out of the plug for single-phase meters.',
    duration: 0.1,
    ...merge(
      mains('s', [168, 176], 10, '10 V 50 Hz', 'supply'),
      neutral('rn', [1096, 160], '(R)', 'r3.plug_n'),
      neutral('ln', [1096, 432], '(R–L)', 'rl_l.plug_n'),
      {
        blocks: [
          [
            'p3',
            'threePhasePowerSensor',
            'Power',
            [424, 176],
            {},
            { label: [80, 0] },
          ],
          [
            'i3',
            'threePhaseCurrentSensor',
            'Currents (R)',
            [680, 160],
            {},
            { label: 'above' },
          ],
          [
            'r3',
            'threePhaseResistor',
            'R 10 Ω',
            [920, 160],
            { R: 10 },
            { label: 'above' },
          ],
          [
            'rl_r',
            'threePhaseResistor',
            'R 10 Ω (R–L)',
            [520, 432],
            { R: 10 },
            { label: 'above' },
          ],
          [
            'il',
            'threePhaseCurrentSensor',
            'Currents (R–L)',
            [720, 432],
            {},
            { label: 'above' },
          ],
          [
            'rl_l',
            'threePhaseInductor',
            'L 31.8 mH',
            [920, 432],
            { L: 0.031831 },
            { label: 'above' },
          ],
          [
            'ic',
            'threePhaseCurrentSensor',
            'Currents (C)',
            [520, 704],
            {},
            { label: 'above' },
          ],
          [
            'cb',
            'threePhaseCapacitor',
            'C 100 µF',
            [760, 704],
            { C: 1e-4 },
            { label: 'above' },
          ],
          ['dl', 'delta', 'Delta', [920, 704], {}, { label: 'above' }],
          ['pa', 'phaseA', 'Phase a', [520, 912], {}, { label: 'above' }],
          ['pb', 'phaseB', 'Phase b', [792, 912], {}, { label: 'above' }],
          ['pc', 'phaseC', 'Phase c', [1064, 912], {}, { label: 'above' }],
          ['va', 'voltageSensor', 'v a', [600, 1040], {}, { label: 'right' }],
          ['vb', 'voltageSensor', 'v b', [872, 1040], {}, { label: 'right' }],
          ['vc', 'voltageSensor', 'v c', [1144, 1040], {}, { label: 'right' }],
          ['vag', 'ground', 'Ground a', [600, 1136]],
          ['vbg', 'ground', 'Ground b', [872, 1136]],
          ['vcg', 'ground', 'Ground c', [1144, 1136]],
        ],
        links: [
          ['s.plug_p', 'p3.pc'],
          ['p3.pc', 'p3.pv'],
          ['p3.nv', 'r3.plug_n'],
          ['p3.nc', 'i3.plug_p'],
          ['i3.plug_n', 'r3.plug_p'],
          ['s.plug_p', 'rl_r.plug_p'],
          ['rl_r.plug_n', 'il.plug_p'],
          ['il.plug_n', 'rl_l.plug_p'],
          ['s.plug_p', 'ic.plug_p'],
          ['ic.plug_n', 'cb.plug_p'],
          ['cb.plug_n', 'dl.plug_n'],
          ['dl.plug_p', 'cb.plug_p'],
          ['s.plug_p', 'pa.plug_p'],
          ['s.plug_p', 'pb.plug_p'],
          ['s.plug_p', 'pc.plug_p'],
          ['pa.pin_p', 'va.p'],
          ['pb.pin_p', 'vb.p'],
          ['pc.pin_p', 'vc.p'],
          ['va.n', 'vag.p'],
          ['vb.n', 'vbg.p'],
          ['vc.n', 'vcg.p'],
        ],
      },
    ),
    plots: [
      {
        label: 'Phase voltages',
        series: ['va.y', 'vb.y', 'vc.y'],
        labels: ['a', 'b', 'c'],
      },
      {
        label: 'Phase a currents',
        series: ['i3.ia', 'il.ia', 'ic.ia'],
        labels: ['R', 'R–L', 'C (delta)'],
      },
      {
        label: 'Resistive load power',
        series: ['p3.power'],
        labels: ['P (W)'],
      },
    ],
    checks: [
      {
        signal: 'p3.power',
        value: 15,
        tol: 1e-3,
        why: '3 · (10 V)² / (2 · 10 Ω), constant in a balanced load',
      },
      {
        signal: 'i3.ia',
        at: 0.085,
        value: 1,
        tol: 1e-3,
        why: '10 V / 10 Ω at the phase a peak',
      },
      {
        signal: 'il.ia',
        at: 0.0875,
        value: 10 / Math.sqrt(200),
        tol: 3e-3,
        why: '10 V / |10 + j10| Ω, 45° after the voltage peak',
      },
      {
        signal: 'ic.ia',
        at: 0.08,
        value: 3 * 10 * 2 * Math.PI * 50 * 1e-4,
        tol: 0.01,
        why: '√3 × the capacitor current √3 · 10 V · ωC, peaking at the phase voltage zero',
      },
      { signal: 'va.y', at: 0.085, value: 10, tol: 1e-3, why: 'phase a peak' },
      {
        signal: 'vb.y',
        at: 0.085,
        value: 10 * Math.sin(Math.PI / 2 - (2 * Math.PI) / 3),
        tol: 1e-3,
        why: 'phase b lags a by 120°',
      },
      {
        signal: 'vc.y',
        at: 0.085,
        value: 10 * Math.sin(Math.PI / 2 + (2 * Math.PI) / 3),
        tol: 1e-3,
        why: 'phase c leads a by 120°',
      },
    ],
    about: [
      'threePhaseResistor',
      'threePhaseInductor',
      'threePhaseCapacitor',
      'star',
      'delta',
      'phaseA',
      'phaseB',
      'phaseC',
      'threePhaseCurrentSensor',
      'threePhasePowerSensor',
    ],
  },
  {
    id: 'three-phase-transformer',
    title: 'Three-phase transformer',
    area: '3-phase',
    summary:
      'A Dy1 transformer with ratio 2 steps 100 V phase voltage down into a star-connected load.',
    description:
      'The ratio 2 halves the line-to-line voltage, so the 100 V peak phase voltage on the delta side becomes about 50 V on the star side, 30° later (vector group Dy1). The load draws about 1 A per phase; the winding resistance and leakage take a little of the voltage. The three-phase voltage sensor reads each output phase against the load star point, which is grounded with the transformer neutral.',
    duration: 0.1,
    ...merge(
      mains('s', [168, 176], 100, '100 V 50 Hz', 'supply'),
      neutral('ln', [936, 176], 'load', 'r.plug_n'),
      {
        blocks: [
          [
            't',
            'threePhaseTransformer',
            'Dy1 transformer',
            [424, 176],
            { n: 2 },
            { label: 'above' },
          ],
          ['tg', 'ground', 'Ground (neutral)', [424, 312]],
          [
            'r',
            'threePhaseResistor',
            'Load 50 Ω',
            [704, 176],
            { R: 50 },
            { label: 'above' },
          ],
          ['v3', 'threePhaseVoltageSensor', 'Output voltages', [704, 400]],
        ],
        links: [
          ['s.plug_p', 't.plug1'],
          ['t.starpoint2', 'tg.p'],
          ['t.plug2', 'r.plug_p'],
          ['v3.plug_p', 'r.plug_p'],
          ['v3.plug_n', 'r.plug_n'],
        ],
      },
    ),
    plots: [
      {
        label: 'Output phase voltages',
        series: ['v3.va', 'v3.vb', 'v3.vc'],
        labels: ['a', 'b', 'c'],
      },
    ],
    checks: [
      {
        signal: 'v3.va',
        min: -50.01,
        max: 50.01,
        why: 'never above half of the 100 V input',
      },
      {
        signal: 'v3.va',
        at: 0.08 + (0.02 * 120) / 360,
        value: 50,
        tol: 1.5,
        why: 'about 50 V, peaking 30° after the input (Dy1)',
      },
    ],
    about: ['threePhaseTransformer', 'threePhaseVoltageSensor'],
  },
  {
    id: 'drivetrain',
    title: 'Rotational drivetrain',
    area: 'Mechanical',
    summary:
      'A torque step drives a motor inertia through a 2:1 gear and a shaft spring into a damped load, with every rotational sensor.',
    description:
      'A 1 N·m step at 0.1 s turns the motor inertia (0.01 kg·m²). The gear halves the speed and doubles the torque, the spring stands for shaft twist, and the load (0.04 kg·m²) spins against a 0.1 N·m·s damper. At steady state the load turns at 2 N·m / 0.1 = 20 rad/s, the motor at 40 rad/s, and 40 W flows through the shaft. The relative-speed sensor shows the shaft twisting back and forth before it settles.',
    duration: 6,
    blocks: [
      [
        'tau',
        'torqueStep',
        'Torque 1 N·m',
        [120, 200],
        { stepTorque: 1, offsetTorque: 0, startTime: 0.1 },
      ],
      [
        'j1',
        'rotInertia',
        'Motor 0.01 kg·m²',
        [320, 200],
        { J: 0.01 },
        { label: 'above' },
      ],
      [
        'gear',
        'idealGear',
        'Gear 2:1',
        [464, 200],
        { ratio: 2 },
        { label: 'above' },
      ],
      [
        'pw',
        'rotPowerSensor',
        'Shaft power',
        [608, 200],
        {},
        { label: 'above' },
      ],
      [
        'tq',
        'torqueSensor',
        'Shaft torque',
        [784, 200],
        {},
        { label: 'above', ports: { b: 'right', y: 'bottom' } },
      ],
      ['k', 'rotSpring', 'Shaft 1000 N·m/rad', [960, 200], { c: 1000 }],
      [
        'j2',
        'rotInertia',
        'Load 0.04 kg·m²',
        [1104, 200],
        { J: 0.04 },
        { label: 'above' },
      ],
      [
        'd',
        'rotDamper',
        'Friction 0.1',
        [1248, 200],
        { d: 0.1 },
        { label: 'above' },
      ],
      ['fix', 'rotFixed', 'Frame', [1360, 296]],
      [
        'acc',
        'rotAccSensor',
        'Motor acceleration',
        [376, 392],
        {},
        { label: 'right' },
      ],
      [
        'dw',
        'relSpeedSensor',
        'Shaft twist rate',
        [960, 72],
        {},
        { label: 'above' },
      ],
      [
        'w2',
        'rotSpeedSensor',
        'Load speed',
        [1152, 392],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['tau.flange', 'j1.flange_a'],
      ['j1.flange_b', 'gear.flange_a'],
      ['gear.flange_b', 'pw.flange_a'],
      ['pw.flange_b', 'tq.a'],
      ['tq.b', 'k.flange_a'],
      ['k.flange_b', 'j2.flange_a'],
      ['j2.flange_b', 'd.flange_a'],
      ['d.flange_b', 'fix.flange'],
      ['j1.flange_b', 'acc.flange'],
      ['dw.flange_a', 'k.flange_a'],
      ['dw.flange_b', 'k.flange_b'],
      ['j2.flange_b', 'w2.flange'],
    ],
    plots: [
      { label: 'Load speed', series: ['w2.w'], labels: ['ω load'] },
      {
        label: 'Shaft torque and power',
        series: ['tq.y', 'pw.power'],
        labels: ['τ (N·m)', 'P (W)'],
      },
      {
        label: 'Motor acceleration and shaft twist rate',
        series: ['acc.a', 'dw.w_rel'],
        labels: ['α motor', 'Δω shaft'],
      },
    ],
    checks: [
      {
        signal: 'w2.w',
        value: 20 * (1 - Math.exp(-5.9 / 0.8)),
        tol: 0.05,
        why: '2 N·m / 0.1 N·m·s, τ = (0.04 + 4 · 0.01) / 0.1 = 0.8 s',
      },
      {
        signal: 'tq.y',
        value: 2,
        tol: 0.02,
        why: 'twice the 1 N·m after the gear',
      },
      { signal: 'pw.power', value: 40, tol: 0.5, why: '2 N·m · 20 rad/s' },
      {
        signal: 'acc.a',
        at: 0.101,
        value: 100,
        tol: 2,
        why: '1 N·m / 0.01 kg·m²: at first only the motor moves, as the shaft has not twisted yet',
      },
      {
        signal: 'dw.w_rel',
        value: 0,
        tol: 0.05,
        why: 'no twisting once settled',
      },
    ],
    about: [
      'torqueStep',
      'rotInertia',
      'idealGear',
      'rotPowerSensor',
      'torqueSensor',
      'rotSpring',
      'rotDamper',
      'rotFixed',
      'rotAccSensor',
      'relSpeedSensor',
      'rotSpeedSensor',
    ],
  },
  {
    id: 'rotational-sources',
    title: 'Clutch, backlash, and rotational sources',
    area: 'Mechanical',
    summary:
      'A clutch that locks, gear backlash, a spring-damper coupling, and a load that steps its torque.',
    description:
      'The clutch closes at 0.5 s and drags its 1 kg·m² load up to the 100 rad/s the speed source reached at 0.1 s, then locks. The backlash leaves the driven inertia standing still until the sine-driven source has taken up half the 0.1 rad gap, at 0.04 s. A torque source of 0.5 N·m drives an inertia with 0.05 N·m·s of damping through a spring-damper, so it settles at 10 rad/s. A constant 0.4 N·m accelerates a shaft load until its load torque steps up at 0.45 s; then it slows down.',
    duration: 2,
    blocks: [
      [
        'w100',
        'step',
        '100 rad/s at 0.1 s',
        [72, 136],
        { height: 100, startTime: 0.1 },
      ],
      ['drv', 'speedSource', 'Drive', [232, 136], { f_crit: 50 }],
      [
        'press',
        'step',
        'Close at 0.5 s',
        [232, 16],
        { height: 1, startTime: 0.5 },
      ],
      ['cl', 'clutch', 'Clutch', [376, 136]],
      [
        'jc',
        'rotInertia',
        'Driven 1 kg·m²',
        [536, 136],
        { J: 1 },
        { label: 'above' },
      ],
      [
        'wc',
        'rotSpeedSensor',
        'Driven speed',
        [744, 136],
        {},
        { label: 'right' },
      ],
      [
        'wref',
        'sine',
        'ω ref 10 sin 2πt',
        [120, 352],
        { amplitude: 10, frequency: 1 },
      ],
      [
        'ss',
        'speedSource',
        'Speed source',
        [320, 352],
        { f_crit: 50 },
        { label: 'above' },
      ],
      [
        'bl',
        'rotBacklash',
        'Backlash 0.1 rad',
        [504, 352],
        { b: 0.1 },
        { label: 'above' },
      ],
      [
        'jb',
        'rotInertia',
        'Inertia 0.01',
        [648, 352],
        { J: 0.01 },
        { label: 'above' },
      ],
      [
        'wb',
        'rotSpeedSensor',
        'Speed behind backlash',
        [848, 352],
        {},
        { label: 'right' },
      ],
      ['tref', 'constant', '0.5 N·m', [120, 568], { value: 0.5 }],
      [
        'tsrc',
        'torqueSource',
        'Torque source',
        [320, 568],
        {},
        { label: 'above' },
      ],
      [
        'cpl',
        'springDamper',
        'Coupling',
        [504, 568],
        { c: 10, d: 0.1 },
        { label: 'above' },
      ],
      [
        'ji',
        'inertia',
        'Inertia 0.02, damping 0.05',
        [696, 616],
        { J: 0.02, damping: 0.05 },
        { label: 'right' },
      ],
      ['ws', 'sensor', 'Coupled speed', [504, 456], {}, { label: 'left' }],
      ['tc', 'constantTorque', '0.4 N·m', [120, 808], { tau_constant: 0.4 }],
      [
        'ld',
        'shaftLoad',
        'Shaft load',
        [376, 808],
        {
          J: 0.002,
          damping: 0.001,
          initialLoad: 0.05,
          stepLoad: 0.35,
          loadTime: 0.45,
        },
        { label: 'right' },
      ],
      [
        'wl',
        'rotSpeedSensor',
        'Load speed',
        [376, 968],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['w100.y', 'drv.w_ref'],
      ['drv.flange', 'cl.flange_a'],
      ['press.y', 'cl.f_normalized'],
      ['cl.flange_b', 'jc.flange_a'],
      ['jc.flange_b', 'wc.flange'],
      ['wref.y', 'ss.w_ref'],
      ['ss.flange', 'bl.flange_a'],
      ['bl.flange_b', 'jb.flange_a'],
      ['jb.flange_b', 'wb.flange'],
      ['tref.y', 'tsrc.tau'],
      ['tsrc.flange', 'cpl.a'],
      ['cpl.b', 'ji.b'],
      ['ji.a', 'ws.flange'],
      ['tc.flange', 'ld.flange'],
      ['tc.flange', 'wl.flange'],
    ],
    plots: [
      { label: 'Clutch', series: ['wc.w'], labels: ['Driven speed'] },
      {
        label: 'Backlash',
        series: ['wref.y', 'wb.w'],
        labels: ['Reference', 'Behind the backlash'],
      },
      {
        label: 'Torque-driven shafts',
        series: ['ws.y', 'wl.w'],
        labels: ['Coupled inertia', 'Shaft load'],
      },
    ],
    checks: [
      { signal: 'wc.w', at: 0.45, value: 0, tol: 1e-6, why: 'clutch open' },
      { signal: 'wc.w', value: 100, tol: 1e-3, why: 'locked to the source' },
      {
        signal: 'wb.w',
        at: 0.03,
        value: 0,
        tol: 1e-6,
        why: 'the gap is not yet taken up',
      },
      {
        signal: 'wb.w',
        at: 0.25,
        value: 10,
        tol: 0.3,
        why: 'in contact: follows the source',
      },
      { signal: 'ws.y', value: 10, tol: 0.1, why: '0.5 N·m / 0.05 N·m·s' },
      {
        signal: 'wl.w',
        at: 0.45,
        value: 350 * (1 - Math.exp(-0.225)),
        tol: 0.5,
        why: '(0.4 − 0.05) N·m against J = 0.002, d = 0.001',
      },
      {
        signal: 'wl.w',
        value: 350 * (1 - Math.exp(-0.225)) * Math.exp(-1.55 / 2),
        tol: 0.5,
        why: 'the load torque now equals the drive: it coasts down with τ = 2 s',
      },
    ],
    about: [
      'clutch',
      'rotBacklash',
      'speedSource',
      'torqueSource',
      'constantTorque',
      'springDamper',
      'shaftLoad',
      'inertia',
      'sensor',
    ],
  },
  {
    id: 'wheel-road',
    title: 'Wheel and rack',
    area: 'Mechanical',
    summary:
      'A wheel turns axle torque into force on a vehicle mass, and a rack and pinion turns speed into travel.',
    description:
      'A constant 30 N·m on a 0.3 m wheel pushes the 100 kg vehicle with 100 N against 10 N·s/m of drag, so it approaches 10 m/s with a time constant of about 10 s (the wheel inertia adds 1.1 kg). The rack and pinion turns 100 rad per metre, so a pinion at 10 rad/s moves the rack 0.1 m every second.',
    duration: 20,
    blocks: [
      ['tq', 'constantTorque', '30 N·m', [120, 200], { tau_constant: 30 }],
      [
        'jw',
        'rotInertia',
        'Wheel 0.1 kg·m²',
        [320, 200],
        { J: 0.1 },
        { label: 'above' },
      ],
      [
        'wh',
        'rollingWheel',
        'Wheel r 0.3 m',
        [488, 200],
        { radius: 0.3 },
        { label: 'above' },
      ],
      [
        'car',
        'mass',
        'Vehicle 100 kg',
        [656, 200],
        { m: 100 },
        { label: 'above' },
      ],
      [
        'drag',
        'transDamper',
        'Drag 10 N·s/m',
        [800, 200],
        { d: 10 },
        { label: 'above' },
      ],
      ['road', 'transFixed', 'Road', [912, 296]],
      [
        'v',
        'velocitySensor',
        'Vehicle speed',
        [720, 392],
        {},
        { label: 'right' },
      ],
      ['w10', 'constantSpeed', 'Pinion 10 rad/s', [120, 584], { w_fixed: 10 }],
      [
        'rack',
        'gearR2T',
        'Rack and pinion',
        [352, 584],
        { ratio: 100 },
        { label: 'above' },
      ],
      ['rm', 'mass', 'Rack 1 kg', [536, 584], { m: 1 }, { label: 'above' }],
      [
        's',
        'positionSensor',
        'Rack position',
        [736, 584],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['tq.flange', 'jw.flange_a'],
      ['jw.flange_b', 'wh.flangeR'],
      ['wh.flangeT', 'car.flange_a'],
      ['car.flange_b', 'drag.flange_a'],
      ['drag.flange_b', 'road.flange'],
      ['car.flange_b', 'v.flange'],
      ['w10.flange', 'rack.flangeR'],
      ['rack.flangeT', 'rm.flange_a'],
      ['rm.flange_b', 's.flange'],
    ],
    plots: [
      { label: 'Vehicle speed', series: ['v.v'], labels: ['v (m/s)'] },
      { label: 'Rack position', series: ['s.s'], labels: ['s (m)'] },
    ],
    checks: [
      {
        signal: 'v.v',
        value: 10 * (1 - Math.exp((-20 / (101 + 1 / 9)) * 10)),
        tol: 0.02,
        why: 'F / d with m = 100 kg + J / r²',
      },
      {
        signal: 's.s',
        value: 2,
        tol: 1e-4,
        why: '10 rad/s / 100 rad/m for 20 s',
      },
    ],
    about: ['rollingWheel', 'gearR2T'],
  },
  {
    id: 'mass-spring-damper',
    title: 'Mass, spring, and damper',
    area: 'Mechanical',
    summary:
      'Two 1 kg masses on 100 N/m springs and 2 N·s/m dampers, pushed by 1 N, with every translational sensor.',
    description:
      'Both systems have a natural frequency of 10 rad/s and a damping ratio of 0.1, so they ring and settle at 1 N / 100 N/m = 1 cm. The upper one uses a combined spring-damper and is pushed by a force step at 0.1 s through a force sensor. The lower one has a separate spring and damper and a force that acts from the start, so it overshoots to 1.73 cm at 0.32 s.',
    duration: 8,
    blocks: [
      [
        'f1',
        'forceStep',
        'Force step 1 N',
        [120, 200],
        { stepForce: 1, offsetForce: 0, startTime: 0.1 },
      ],
      [
        'fs',
        'forceSensor',
        'Applied force',
        [320, 200],
        {},
        { label: 'above' },
      ],
      ['m1', 'mass', 'Mass 1 kg', [464, 200], { m: 1 }, { label: 'above' }],
      [
        'sd',
        'transSpringDamper',
        'Spring-damper',
        [608, 200],
        { c: 100, d: 2 },
        { label: 'above' },
      ],
      ['wall1', 'transFixed', 'Wall', [720, 296]],
      ['x1', 'positionSensor', 'Position', [264, 392], {}, { label: 'right' }],
      ['v1', 'velocitySensor', 'Velocity', [520, 392], {}, { label: 'right' }],
      [
        'a1',
        'transAccSensor',
        'Acceleration',
        [776, 392],
        {},
        { label: 'right' },
      ],
      ['f2', 'constantForce', 'Force 1 N', [120, 632], { f_constant: 1 }],
      [
        'm2',
        'mass',
        'Mass 1 kg (lower)',
        [320, 632],
        { m: 1 },
        { label: 'above' },
      ],
      [
        'k2',
        'transSpring',
        'Spring 100 N/m',
        [496, 584],
        { c: 100 },
        { label: 'above' },
      ],
      ['d2', 'transDamper', 'Damper 2 N·s/m', [496, 696], { d: 2 }],
      ['wall2', 'transFixed', 'Wall (lower)', [656, 792]],
      [
        'ds',
        'relPositionSensor',
        'Spring compression',
        [672, 504],
        {},
        { label: 'above' },
      ],
      [
        'x2',
        'positionSensor',
        'Position (lower)',
        [320, 824],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['f1.flange', 'fs.flange_a'],
      ['fs.flange_b', 'm1.flange_a'],
      ['m1.flange_b', 'sd.flange_a'],
      ['sd.flange_b', 'wall1.flange'],
      ['m1.flange_a', 'x1.flange'],
      ['m1.flange_b', 'v1.flange'],
      ['m1.flange_b', 'a1.flange'],
      ['f2.flange', 'm2.flange_a'],
      ['m2.flange_b', 'k2.flange_a'],
      ['m2.flange_b', 'd2.flange_a'],
      ['k2.flange_b', 'wall2.flange'],
      ['d2.flange_b', 'wall2.flange'],
      ['ds.flange_a', 'k2.flange_a'],
      ['ds.flange_b', 'k2.flange_b'],
      ['m2.flange_a', 'x2.flange'],
    ],
    plots: [
      {
        label: 'Positions',
        series: ['x1.s', 'x2.s'],
        labels: ['Upper', 'Lower'],
      },
      {
        label: 'Upper mass',
        series: ['v1.v', 'a1.a', 'fs.f'],
        labels: ['v (m/s)', 'a (m/s²)', 'F (N)'],
      },
    ],
    checks: [
      { signal: 'x1.s', value: 0.01, tol: 1e-4, why: '1 N / 100 N/m' },
      { signal: 'x2.s', value: 0.01, tol: 1e-4, why: '1 N / 100 N/m' },
      {
        signal: 'x2.s',
        at: Math.PI / (10 * Math.sqrt(1 - 0.01)),
        value: 0.01 * (1 + Math.exp((-Math.PI * 0.1) / Math.sqrt(1 - 0.01))),
        tol: 1e-4,
        why: 'peak overshoot of a ζ = 0.1 system',
      },
      { signal: 'fs.f', value: 1, tol: 1e-6, why: 'the applied 1 N' },
      {
        signal: 'a1.a',
        at: 0.1001,
        value: 1,
        tol: 0.01,
        why: 'F / m at the instant of the step',
      },
      { signal: 'v1.v', value: 0, tol: 1e-4, why: 'at rest' },
      {
        signal: 'ds.s_rel',
        value: -0.01,
        tol: 1e-4,
        why: 'the wall end is 1 cm behind the mass end',
      },
    ],
    about: [
      'mass',
      'transSpringDamper',
      'transSpring',
      'transDamper',
      'transFixed',
      'forceStep',
      'constantForce',
      'forceSensor',
      'positionSensor',
      'velocitySensor',
      'transAccSensor',
      'relPositionSensor',
    ],
  },
  {
    id: 'end-stops',
    title: 'End stops and motion sources',
    area: 'Mechanical',
    summary:
      'A sliding mass that hits its stops, a mass pushed into an elastic stop, and masses driven by speed and position sources.',
    description:
      'The mass with stops is shaken by ±20 N; it sticks until the force overcomes its friction, then slides and stays against the +0.5 m stop while the force pushes it there. The elastic stop starts level with its mass, and its gap of −5 cm gives 5 cm of free travel: the mass pushed by 10 N crosses it and comes to rest pressing 10 µm into the stop. The speed source moves its mass at 0.2 m/s, and the position source makes its mass follow a 0.1 m sine.',
    duration: 2,
    blocks: [
      [
        'fsig',
        'sine',
        '20 sin(πt) N',
        [120, 200],
        { amplitude: 20, frequency: 0.5 },
      ],
      [
        'fsrc',
        'forceSource',
        'Force source',
        [320, 200],
        {},
        { label: 'above' },
      ],
      [
        'ms',
        'massStops',
        'Mass with stops',
        [512, 200],
        { m: 1, smax: 0.5, smin: -0.5 },
        { label: 'above' },
      ],
      [
        'xs',
        'positionSensor',
        'Position (stops)',
        [712, 200],
        {},
        { label: 'right' },
      ],
      ['push', 'constantForce', 'Push 10 N', [120, 440], { f_constant: 10 }],
      ['mh', 'mass', 'Mass 1 kg', [320, 440], { m: 1 }, { label: 'above' }],
      [
        'hs',
        'hardStop',
        'Elastic stop',
        [464, 440],
        { c: 1e6, d: 100, s_rel0: -0.05 },
        { label: 'above' },
      ],
      [
        'wall',
        'transFixed',
        'Stop at 0.1 m',
        [576, 536],
        { s0: 0.1 },
        { label: 'right' },
      ],
      [
        'xh',
        'positionSensor',
        'Position (elastic stop)',
        [264, 632],
        {},
        { label: 'right' },
      ],
      ['vref', 'constant', '0.2 m/s', [120, 824], { value: 0.2 }],
      [
        'vs',
        'transSpeedSource',
        'Speed source',
        [320, 824],
        {},
        { label: 'above' },
      ],
      [
        'mv',
        'mass',
        'Mass 1 kg (speed)',
        [504, 824],
        { m: 1 },
        { label: 'above' },
      ],
      [
        'vv',
        'velocitySensor',
        'Velocity (speed source)',
        [704, 824],
        {},
        { label: 'right' },
      ],
      [
        'sref',
        'sine',
        '0.1 sin(πt) m',
        [120, 1032],
        { amplitude: 0.1, frequency: 0.5 },
      ],
      [
        'ps',
        'positionSource',
        'Position source',
        [320, 1032],
        {},
        { label: 'above' },
      ],
      [
        'mp',
        'mass',
        'Mass 1 kg (position)',
        [504, 1032],
        { m: 1 },
        { label: 'above' },
      ],
      [
        'xp',
        'positionSensor',
        'Position (position source)',
        [704, 1032],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['fsig.y', 'fsrc.f'],
      ['fsrc.flange', 'ms.flange_a'],
      ['ms.flange_b', 'xs.flange'],
      ['push.flange', 'mh.flange_a'],
      ['mh.flange_b', 'hs.flange_a'],
      ['hs.flange_b', 'wall.flange'],
      ['mh.flange_a', 'xh.flange'],
      ['vref.y', 'vs.v_ref'],
      ['vs.flange', 'mv.flange_a'],
      ['mv.flange_b', 'vv.flange'],
      ['sref.y', 'ps.s_ref'],
      ['ps.flange', 'mp.flange_a'],
      ['mp.flange_b', 'xp.flange'],
    ],
    plots: [
      {
        label: 'Stops',
        series: ['xs.s', 'xh.s'],
        labels: ['Mass with stops', 'Elastic stop'],
      },
      {
        label: 'Driven masses',
        series: ['vv.v', 'xp.s'],
        labels: ['Velocity (speed source)', 'Position (position source)'],
      },
    ],
    checks: [
      {
        signal: 'xs.s',
        min: -0.5001,
        max: 0.5001,
        why: 'never beyond the stops',
      },
      {
        signal: 'xs.s',
        at: 0.9,
        value: 0.5,
        tol: 1e-6,
        why: 'held against the upper stop',
      },
      {
        signal: 'xh.s',
        value: 0.15 + 1e-5,
        tol: 1e-4,
        why: 'starts at the wall position 0.1 m, travels the 5 cm free length, then compresses 10 N / 10⁶ N/m',
      },
      { signal: 'vv.v', value: 0.2, tol: 1e-4, why: 'the reference speed' },
      {
        signal: 'xp.s',
        at: 0.5,
        value: 0.1,
        tol: 2e-3,
        why: 'follows the reference peak at 0.5 s',
      },
    ],
    about: [
      'massStops',
      'hardStop',
      'forceSource',
      'transSpeedSource',
      'positionSource',
    ],
  },
  {
    id: 'cooling',
    title: 'Cooling a hot part',
    area: 'Thermal',
    summary:
      'A 10 W part cools through a thermal resistance into a heatsink that convects and radiates to 20 °C.',
    description: `The part dissipates 10 W. It reaches the heatsink through 2 K/W, and the heatsink loses heat by convection (5 W/K, set by a signal) and by radiation. At steady state the heatsink sits ${(hs - 273.15).toFixed(1)} °C and the part 20 K hotter; the heat flow sensor reads the full 10 W. Below, a prescribed temperature holds one side of a 1 W/K conductor at 350 K while a prescribed heat flow adds 20 W from 1500 s, which lifts the body 20 K above it.`,
    duration: 3000,
    blocks: [
      ['q', 'fixedHeatFlow', '10 W', [104, 200], { Q_flow: 10 }],
      [
        'part',
        'heatCapacitor',
        'Part 100 J/K',
        [264, 104],
        { C: 100 },
        { label: 'above' },
      ],
      [
        'qflow',
        'heatFlowSensor',
        'Heat flow',
        [424, 200],
        {},
        { label: 'above' },
      ],
      [
        'rth',
        'thermalResistor',
        'R 2 K/W',
        [584, 200],
        { R: 2 },
        { label: 'above' },
      ],
      [
        'sink',
        'heatCapacitor',
        'Heatsink 500 J/K',
        [744, 104],
        { C: 500 },
        { label: 'above' },
      ],
      ['h', 'constant', 'h·A 5 W/K', [848, 16], { value: 5 }],
      [
        'conv',
        'convection',
        'Convection',
        [936, 200],
        {},
        { ports: { Gc: ['top', 25] } },
      ],
      [
        'air',
        'fixedTemperature',
        'Air 20 °C',
        [1128, 200],
        { T: 293.15 },
        { rotation: 180, label: 'right' },
      ],
      [
        'rad',
        'radiation',
        'Radiation',
        [936, 344],
        { Gr: 0.01 },
        { label: 'above' },
      ],
      [
        'room',
        'fixedTemperature',
        'Room 20 °C',
        [1128, 344],
        { T: 293.15 },
        { rotation: 180, label: 'right' },
      ],
      [
        'Tp',
        'temperatureSensor',
        'Part temperature',
        [264, 344],
        {},
        { label: 'right' },
      ],
      ['dT', 'relTemperatureSensor', 'Across R', [584, 344]],
      ['Tset', 'constant', '350 K', [104, 568], { value: 350 }],
      [
        'hold',
        'prescribedTemperature',
        'Held at 350 K',
        [264, 568],
        {},
        { label: 'above' },
      ],
      [
        'g',
        'thermalConductor',
        'G 1 W/K',
        [424, 568],
        { G: 1 },
        { label: 'above' },
      ],
      [
        'body',
        'heatCapacitor',
        'Body 100 J/K',
        [584, 488],
        { C: 100 },
        { label: 'above' },
      ],
      [
        'qset',
        'step',
        '20 W at 1500 s',
        [424, 712],
        { height: 20, startTime: 1500 },
      ],
      [
        'heat',
        'prescribedHeatFlow',
        'Heater',
        [584, 712],
        {},
        { label: 'right', ports: { port: 'top' } },
      ],
      [
        'Tb',
        'temperatureSensor',
        'Body temperature',
        [776, 568],
        {},
        { label: 'right' },
      ],
    ],
    links: [
      ['q.port', 'part.port'],
      ['part.port', 'qflow.port_a'],
      ['qflow.port_b', 'rth.port_a'],
      ['rth.port_b', 'sink.port'],
      ['sink.port', 'conv.solid'],
      ['h.y', 'conv.Gc'],
      ['conv.fluid', 'air.port'],
      ['sink.port', 'rad.port_a'],
      ['rad.port_b', 'room.port'],
      ['part.port', 'Tp.port'],
      ['dT.port_a', 'rth.port_a'],
      ['dT.port_b', 'rth.port_b'],
      ['Tset.y', 'hold.T'],
      ['hold.port', 'g.port_a'],
      ['g.port_b', 'body.port'],
      ['qset.y', 'heat.Q_flow'],
      ['heat.port', 'body.port'],
      ['body.port', 'Tb.port'],
    ],
    plots: [
      { label: 'Part temperature', series: ['Tp.T'], labels: ['T part (K)'] },
      {
        label: 'Heat flow and drop across R',
        series: ['qflow.Q_flow', 'dT.T_rel'],
        labels: ['Q (W)', 'ΔT (K)'],
      },
      { label: 'Body temperature', series: ['Tb.T'], labels: ['T body (K)'] },
    ],
    checks: [
      {
        signal: 'Tp.T',
        value: hs + 20,
        tol: 0.05,
        why: 'heatsink balance of convection and radiation, plus 10 W · 2 K/W',
      },
      {
        signal: 'qflow.Q_flow',
        value: 10,
        tol: 0.01,
        why: 'all of the 10 W flows to the heatsink',
      },
      {
        signal: 'dT.T_rel',
        value: 20,
        tol: 0.02,
        why: 'port a is 10 W · 2 K/W hotter than port b',
      },
      {
        signal: 'Tb.T',
        at: 1400,
        value: 350,
        tol: 0.01,
        why: 'held at 350 K through 1 W/K',
      },
      {
        signal: 'Tb.T',
        value: 370,
        tol: 0.01,
        why: '20 W / 1 W/K above 350 K',
      },
    ],
    about: [
      'heatCapacitor',
      'fixedHeatFlow',
      'heatFlowSensor',
      'thermalResistor',
      'convection',
      'fixedTemperature',
      'radiation',
      'temperatureSensor',
      'relTemperatureSensor',
      'prescribedTemperature',
      'thermalConductor',
      'prescribedHeatFlow',
    ],
  },
  {
    id: 'magnetic-core',
    title: 'Magnetic circuits',
    area: 'Magnetic',
    summary:
      'A 100-turn winding drives flux through an air gap and a core, next to magnetic sources and a variable reluctance.',
    description:
      'The winding carries 1 A from 1 V through 1 Ω, so it drives 100 A of magnetomotive force round a gap of 10⁶ A/Wb and a core of 10⁵ A/Wb: 90.9 µWb, with 90.9 A of it across the gap. Its inductance N² / R_m = 9.1 mH sets the 9.1 ms rise. Beside it, a constant 100 A drives a reluctance that swings between 1 and 3 · 10⁶ A/Wb, a signal source drives 50 A through a permeance of 1 µWb/A, and a flux source forces 1 mWb through 10⁶ A/Wb, which takes 1000 A.',
    duration: 0.1,
    blocks: [
      ['v', 'dcSource', '1 V', [120, 232], { V: 1 }, { label: 'left' }],
      ['vg', 'ground', 'Ground', [120, 336]],
      ['r', 'resistor', 'R 1 Ω', [264, 168], { R: 1 }, { label: 'above' }],
      [
        'coil',
        'winding',
        'Winding 100 turns',
        [440, 184],
        { N: 100 },
        { label: 'above' },
      ],
      ['phi', 'fluxSensor', 'Core flux', [648, 168], {}, { label: 'above' }],
      ['gap', 'reluctance', 'Air gap', [808, 168]],
      [
        'core',
        'permeance',
        'Core',
        [968, 264],
        { G_m: 1e-5 },
        { rotation: 90, label: 'right' },
      ],
      ['mg', 'magneticGround', 'Magnetic ground', [520, 480]],
      ['umm', 'mmfSensor', 'Gap mmf', [808, 48], {}, { label: 'above' }],
      [
        'src',
        'mmfSource',
        'mmf 100 A',
        [264, 600],
        { V_m: 100 },
        { rotation: 180 },
      ],
      ['mg2a', 'magneticGround', 'Ground (mmf)', [120, 696]],
      [
        'rm',
        'sine',
        'R_m signal',
        [304, 480],
        { amplitude: 1e6, offset: 2e6, frequency: 5 },
      ],
      ['vr', 'variableReluctance', 'Variable reluctance', [464, 600]],
      ['phi2', 'fluxSensor', 'Flux (variable)', [632, 600]],
      ['mg2', 'magneticGround', 'Ground (variable)', [776, 696]],
      ['u', 'step', '50 A', [136, 800], { height: 50, startTime: 0 }],
      [
        'smmf',
        'signalMmfSource',
        'Signal mmf',
        [296, 896],
        {},
        { rotation: 180, ports: { V_m: 'bottom' } },
      ],
      ['mg3a', 'magneticGround', 'Ground (signal)', [136, 992]],
      ['perm', 'permeance', 'Permeance 1 µWb/A', [456, 896], { G_m: 1e-6 }],
      ['phi3', 'fluxSensor', 'Flux (permeance)', [632, 896]],
      ['mg3', 'magneticGround', 'Ground (permeance)', [776, 992]],
      ['fsrc', 'fluxSource', 'Flux 1 mWb', [1048, 600], { Phi: 1e-3 }],
      ['mg4a', 'magneticGround', 'Ground (flux)', [920, 696]],
      ['rr', 'reluctance', 'Reluctance 10⁶', [1224, 600], { R_m: 1e6 }],
      ['umm2', 'mmfSensor', 'mmf across', [1224, 480], {}, { label: 'above' }],
      ['mg4', 'magneticGround', 'Ground (reluctance)', [1368, 696]],
    ],
    links: [
      ['v.n', 'vg.p'],
      ['v.p', 'r.p'],
      ['r.n', 'coil.p'],
      ['coil.n', 'v.n'],
      ['coil.port_p', 'phi.port_p'],
      ['phi.port_n', 'gap.port_p'],
      ['gap.port_n', 'core.port_p'],
      ['core.port_n', 'coil.port_n'],
      ['coil.port_n', 'mg.port'],
      ['umm.port_p', 'gap.port_p'],
      ['umm.port_n', 'gap.port_n'],
      ['src.port_n', 'mg2a.port'],
      ['src.port_p', 'vr.port_p'],
      ['rm.y', 'vr.R_m'],
      ['vr.port_n', 'phi2.port_p'],
      ['phi2.port_n', 'mg2.port'],
      ['u.y', 'smmf.V_m'],
      ['smmf.port_n', 'mg3a.port'],
      ['smmf.port_p', 'perm.port_p'],
      ['perm.port_n', 'phi3.port_p'],
      ['phi3.port_n', 'mg3.port'],
      ['fsrc.port_p', 'mg4a.port'],
      ['fsrc.port_n', 'rr.port_p'],
      ['rr.port_n', 'mg4.port'],
      ['umm2.port_p', 'rr.port_p'],
      ['umm2.port_n', 'rr.port_n'],
    ],
    plots: [
      {
        label: 'Winding flux and gap mmf',
        series: ['phi.Phi', 'umm.V_m'],
        labels: ['Φ (Wb)', 'V_m gap (A)'],
      },
      {
        label: 'Source circuits',
        series: ['phi2.Phi', 'phi3.Phi'],
        labels: ['Variable reluctance', 'Permeance'],
      },
    ],
    checks: [
      {
        signal: 'phi.Phi',
        value: 100 / 1.1e6,
        tol: 1e-7,
        why: '100 A over 1.1 · 10⁶ A/Wb',
      },
      {
        signal: 'phi.Phi',
        at: 0.0091,
        value: (100 / 1.1e6) * (1 - Math.exp(-1)),
        tol: 1e-6,
        why: 'one L/R time constant',
      },
      {
        signal: 'umm.V_m',
        value: 100 / 1.1,
        tol: 0.01,
        why: 'the gap takes 10/11 of the mmf',
      },
      {
        signal: 'phi2.Phi',
        at: 0.05,
        value: 100 / 3e6,
        tol: 1e-9,
        why: '100 A over 3 · 10⁶ A/Wb',
      },
      { signal: 'phi3.Phi', value: 5e-5, tol: 1e-9, why: '50 A · 1 µWb/A' },
      {
        signal: 'umm2.V_m',
        value: 1000,
        tol: 1e-3,
        why: '1 mWb · 10⁶ A/Wb: the source drives its flux out of n into the reluctance',
      },
    ],
    about: [
      'winding',
      'reluctance',
      'permeance',
      'magneticGround',
      'fluxSensor',
      'mmfSensor',
      'mmfSource',
      'variableReluctance',
      'signalMmfSource',
      'fluxSource',
    ],
  },
];
